// function getArrayInStraitOrder(length) {
//   let arr = [];
//   for (var i = 0; i < array.length; i++) {
//     const element = parseInt(prompt(`${i} element = `))
//     arr.push()
//   }
//   return arr
// }

// function getArrayInStraitOrder(length) {
//   let arr = [];
//   for (var i = 0; i < array.length; i++) {
//     const element = parseInt(prompt(`${i} element = `))
//     arr.unshift()
//   }
//   return arr
// }


// function getArrayInStraitOrder(length) {
//   let a = [2, 5, 2, 54, 7, 2];
//   for (var i = 0; i < a.length; i++) {
//       console.log(a[i]);
//   }
//   return arr
// }

// function getArrayInStraitOrder(length) {
//   let a = [72, 5, 2, 54, 7, 2];
//   for (var i = 0; i < a.length; i++) {
//       element = a.shift();
//   }
//   return a
// }

// function getArrayInStraitOrder(length) {
//   let a = [72, 5, 2, 54, 7, 2];
//   for (var i = 0; i < a.length; i++) {
//       element = a.pop();
//   }
//   return a
// }

// let a = [1, 2, 3, 7, 9, 7, 6];
// let b = []
// for (var i = 0; i < a.length; i++) {
//   b.push(a[i])
//   if (a[i] ===7) {
//     b.push(8)
//
//   }
// }

// let a = [1, 2, 3, 7, 9, 7, 6];
// let b = []
// for (const el of a) {
//   b.push(el)
//   if (a[i] ===7) b.push(8);
//   }

// let a = [1, 2, 3, 7, 9, 7, 6];
// let elementForInsert = 8;
// for (let i = 0; i < array.length; i++) {
//   if (a[i] === 7) {
//     a.spice(i+1, 0 , elementForInsert)
//     i++
//   }
// }




// Змінити 7 на 8
// let b = []
// for (const el of a) {
//   b.push(el);
//   }

  // зміна існуючого масиву
  // let elementForReplace = 8;
  // for (let i = 0; i < array.length; i++) {
  //   if (a[i] === 7) {
  //     a.spice(i, 1, elementForReplace)
  //   }
  // }

// let a = [1, 2, 3, 7, 9, 7, 6];
// let pos_3= a.indexOf(3)
// if (pos_3 === -1) {
//   alert ('No 7 ')
//   else {
//     let b = a.slice(pos_3)
//   }
//
// }

// let el = [1, -2, 2, 3, -4];
// let sum = arr.reduce((newRes, el) => newRes(el>0) + newRes);
//
// document.write(`${sum}`)
